### ISSUE TITLE
Hi is this the latest OC 0.6.3?

### ISSUE THREAD

**Issue by marcustut** [mBilG/Hackintosh-TongFang-GK5CP0Y#1]
I came across your repo when I look for successful example Opencore Hackintosh on Illegear laptop, I have the Raven SE with i7-9750h and GTX1650ti, I think most of the other part are quite similar, and the GPU doesn't matter much since will be using iGPU under macOS.

But want to make sure is this the latest version of OpenCore and is there any bugs or issues with your installation? 

Thanks in advance.

**Comment by mBilG** [comment]
I think it's still on 6.0
I'm not using that laptop now
If you want the latest OC, refer to this Github page:
https://github.com/kirainmoe/tongfang-hackintosh-utility
I got my EFI from there.

As for bugs, I did not notice any during the time I was using the PC. Only thing was iMessage and FaceTime were not working.. But there are fixes for those that I didn't have time to check.

**Comment by marcustut** [comment]
Yo thanks for the reply, I've tried Tongfang-hackintosh-utility and it's working pretty fine on OC 0.6.3 except for the touchpad, click is not working, does this happens to you too?

**Comment by mBilG** [comment]
Mine was working fine.. you may need to select a different device from the list and try. I got mine to work by trial and error.
